version: '3.4'

services:
  web:
    container_name: mc-compromiso-web
    restart: always
    build:
      context: ./web
      args: 
      - NEXT_PUBLIC_STRAPI_URL=${STRAPI_URL_PUBLIC}
      - STRAPI_URL_BUILD=${STRAPI_URL_BUILD}
      - NEXT_PUBLIC_GOOGLE_API=${GOOGLE_API_FRONT}
      - GOOGLE_API_BACK=${GOOGLE_API_BACK}
      - NEXT_PUBLIC_reCAPTCHA_SITE=${RECAPTCHA_SITE}
      - reCAPTCHA_SECRET=${RECAPTCHA_SECRET}
      - STRAPI_API_KEY=${STRAPI_API_KEY}
      network: compromiso_default
    expose: 
      - "3000"
    environment:
      - NEXT_PUBLIC_STRAPI_URL=${STRAPI_URL_PUBLIC}
      - STRAPI_URL_BUILD=${STRAPI_URL_BUILD}
      - NEXT_PUBLIC_GOOGLE_API=${GOOGLE_API_FRONT}
      - GOOGLE_API_BACK=${GOOGLE_API_BACK}
      - NEXT_PUBLIC_reCAPTCHA_SITE=${RECAPTCHA_SITE}
      - reCAPTCHA_SECRET=${RECAPTCHA_SECRET}
      - STRAPI_API_KEY=${STRAPI_API_KEY}
      - VIRTUAL_HOST=compromiso.mercadocentral.gob.ar,www.compromiso.mercadocentral.gob.ar,compromisosocialdeabastecimiento.gob.ar,www.compromisosocialdeabastecimiento.gob.ar
      - LETSENCRYPT_HOST=compromiso.mercadocentral.gob.ar,www.compromiso.mercadocentral.gob.ar,compromisosocialdeabastecimiento.gob.ar,www.compromisosocialdeabastecimiento.gob.ar
    depends_on:    
      - strapi
    networks: 
      - default
      - compromiso

  strapi:
    container_name: mc-compromiso-strapi
    restart: always
    build: ./strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: mc-api
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${MONGO_USER}
      DATABASE_PASSWORD: ${MONGO_PASS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    expose:
      - "1337"
    links:
      - mongo:mongo
    depends_on: 
      - mongo
    environment:
      - STRAPI_API_KEY=${STRAPI_API_KEY} 
      - VIRTUAL_HOST=api.compromiso.mercadocentral.gob.ar
      - LETSENCRYPT_HOST=api.compromiso.mercadocentral.gob.ar
    volumes:
      - ./data/strapi/uploads:/usr/src/app/public/uploads
    depends_on:
      - mongo
    networks: 
      - default
      - compromiso

  mongo:
    container_name: mc-compromiso-db
    restart: always
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./data/mongo:/data/db
      - ./db-dump:/dump
    expose:
      - "27017"
    ports:
      - "7000:27017"

networks:
  compromiso:
    external: true

