version: '3'

services:

  web:
    container_name: bocas-web
    restart: unless-stopped    
    image: node:14-buster-slim
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn run dev"
    volumes:
      - ./bocas-blog:/usr/src/app
    environment:
      - NEXT_PUBLIC_URL=${STRAPI_URL_PUBLIC}
      - STRAPI_URL_BUILD=${STRAPI_URL_BUILD}
      - STRAPI_API_KEY=${STRAPI_API_KEY}
    ports: 
      - 3000:3000
    networks: 
      - bocas-services
    depends_on: 
      - strapi

  strapi:
    container_name: bocas-strapi
    restart: unless-stopped
    image: strapi/strapi:alpine
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: mc-api
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${MONGO_USER}
      DATABASE_PASSWORD: ${MONGO_PASS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    volumes:
      - ./strapi:/srv/app
      - ./data/strapi/uploads:/srv/app/public/uploads
    ports:
      - 1337:1337    
    networks: 
      - bocas-services
    depends_on: 
      - mongo
    environment: 
      - STRAPI_API_KEY=${STRAPI_API_KEY}
      
  mongo:
    container_name: bocas-mongo
    restart: unless-stopped
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports: 
      - 7000:27017
    volumes:
      - ./data/mongo:/data/db
      - ./db-dump:/dump
    expose:
      - "27017"
    networks: 
      - bocas-services

networks: 
    bocas-services:
        driver: bridge

  




