version: '3.4'

services:

  nginx-proxy:
    container_name: bocas-nginx
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - bocas-services
    volumes:      
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    
  letsencrypt:
    container_name: bocas-letsencrypt
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=bocas-nginx
      - DEFAULT_EMAIL=p.miroslav.sapunar@gmail.com
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: 
      - nginx-proxy
    networks: 
      - bocas-services
  
  web:
    container_name: bocas-web
    restart: always
    build:
      context: ./bocas-blog
      args: 
      - NEXT_PUBLIC_URL_STRAPI=${NEXT_PUBLIC_URL_STRAPI}
      - STRAPI_URL_BUILD=${STRAPI_URL_BUILD}
      - STRAPI_API_KEY=${STRAPI_API_KEY}
      - IG_TEST_TOKEN=${IG_TEST_TOKEN}
      - APP_CLIENT_TOKEN=${APP_CLIENT_TOKEN}
      - GOOGLE_TAG=${GOOGLE_TAG}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS=${NEXT_PUBLIC_GOOGLE_ANALYTICS}
      network: bocas-blog-fullstack_bocas-services
    ports:
      - "3000:3000"
    networks: 
      - bocas-services
    environment:
      - NEXT_PUBLIC_URL_STRAPI=${NEXT_PUBLIC_URL_STRAPI}
      - STRAPI_URL_BUILD=${STRAPI_URL_BUILD}
      - STRAPI_API_KEY=${STRAPI_API_KEY}
      - IG_TEST_TOKEN=${IG_TEST_TOKEN}
      - APP_CLIENT_TOKEN=${APP_CLIENT_TOKEN}
      - GOOGLE_TAG=${GOOGLE_TAG}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS=${NEXT_PUBLIC_GOOGLE_ANALYTICS}
      - VIRTUAL_HOST=blog.bocas.com.ar, www.blog.bocas.com.ar
      - LETSENCRYPT_HOST=blog.bocas.com.ar
    depends_on:    
      - strapi

  strapi:
    container_name: bocas-strapi
    restart: always
    build: ./strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: mc-api
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${MONGO_USER}
      DATABASE_PASSWORD: ${MONGO_PASS}
    ports: 
      - "1337:1337"
    networks: 
      - bocas-services
    depends_on: 
      - mongo
    environment:
      - STRAPI_API_KEY=${STRAPI_API_KEY}
      - VIRTUAL_HOST=apis.blog.bocas.com.ar
      - LETSENCRYPT_HOST=apis.blog.bocas.com.ar
    volumes:
      - data_strapi:/usr/src/app/public/uploads
    depends_on:
      - mongo
      - nginx-proxy      
      - letsencrypt

  strapi-dev:
    container_name: bocas-strapi-dev
    restart: unless-stopped
    image: strapi/strapi:3-node12-alpine
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: bocas-api
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${MONGO_USER}
      DATABASE_PASSWORD: ${MONGO_PASS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    networks: 
      - bocas-services
    volumes:
      - ./strapi:/srv/app
      - data_strapi:/srv/app/public/uploads
    ports:
      - 1338:1337    
    depends_on: 
      - mongo
    environment: 
      - STRAPI_API_KEY=${STRAPI_API_KEY}

  mongo:
    container_name: bocas-db
    restart: always
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - data_mongo:/data/db
      - db_dump:/dump
    ports: 
      - 7000:27017
    expose: 
      - "27017"
    networks: 
    - bocas-services

networks: 
  bocas-services:
    driver: bridge

volumes:
  data_strapi:
  data_mongo:
  db_dump:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  netdatalib:
  netdatacache:
